### PR TITLE
Add some more info on goals to README.md; provide links explaining what's here

### PR DESCRIPTION
**Pull request by davidlmobley**
This adds material to the README.md to explain a little more about what's here and gives some links to the material already present.

### CODE REVIEW

**Comment by davidlmobley** [comment]
(Feel free to preview on my fork to see what this looks like on GitHub, @kofke -- https://github.com/mobleylab/Mol-Sim-Intro ; I hope this is helpful. I'm going to start taking a look through the materials you have here now as well.)

**Comment by kofke** [comment]
Thanks David.  FYI, I probably won’t be able to do anything more with this for the rest of the month, as October is extremely busy for me.  Hope to get back to it next month.

**Comment by davidlmobley** [comment]
Thanks. What would be most helpful, @kofke , would be just if you took a very quick look to see if you're happy with my overall directions. Since I DO have some time to work on it, I could plunge ahead (especially in terms of gathering material you DON'T have -- see #2 -- and updating figures); otherwise to avoid treading on your toes I'll wait until hearing back from you in November.

**Comment by davidlmobley** [comment]
To make it easier to proceed, I'm going to merge this for now (it doesn't change anything major, just improves organization) and we can always rollback if you're unhappy later, @kofke .

**Pull request merged**
